name: Build and release Electron app

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Setup Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16.9.1

      - name: Run electron-builder
        uses: samuelmeuli/action-electron-builder@v1
        with:
          package_root: electron
          github_token: ${{ secrets.github_token }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: |
            electron/out/*dmg*
            electron/out/*AppImage*
            electron/out/*exe*
            electron/out/latest*

  release:
    needs: build

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3

      - name: Upload binaries to release
        uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            out/*dmg*
            out/*AppImage*
            out/*exe*
            out/latest*

      - name: Delete build artifacts
        uses: geekyeggo/delete-artifact@dc8092f14c4245ef6a3501b1669b171c12899167
        with:
          name: out
